/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testnggradle;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;

import org.testng.annotations.Test;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    
    @Test void getMessageTest() {
        Library obj = new Library();
        assertEquals(obj.getMessage(), "Hello , how are you today !!!");
    }
}
