/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testnggradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }   

    public String getMessage() {
        return "Hello , how are you today !!!";
    }
}
